// Isolated PostgreSQL verification: never connects to a remote database.
// Install pinned PGlite in a temporary tools directory and set its module path.
const { PGlite } = await import(process.env.ACTIVITY_PGLITE_MODULE ?? '@electric-sql/pglite');
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const db = new PGlite();
const org='00000000-0000-4000-8000-000000000001';
const other='00000000-0000-4000-8000-000000000009';
const actor='00000000-0000-4000-8000-000000000003';
const member='00000000-0000-4000-8000-000000000002';
await db.exec(`
create schema app; create role anon; create role authenticated;
create function app.is_platform_admin() returns boolean language sql as $$select coalesce(current_setting('test.admin',true)='true',false)$$;
create function app.has_platform_permission(text) returns boolean language sql as $$select coalesce(current_setting('test.permission',true)='true',false)$$;
create table organizations(id uuid primary key);
create table staff_memberships(id uuid primary key,organization_id uuid,user_id uuid,first_name text,last_name text,email text,role text,access_status text,created_at timestamptz);
create table platform_admins(user_id uuid primary key,email text);
create table members(id uuid primary key,organization_id uuid,first_name text,last_name text,deleted_at timestamptz);
create table admin_audit_log(id bigint primary key,admin_id uuid,action text,target_organization_id uuid,at timestamptz,metadata jsonb,detail jsonb,entity_type text,entity_id text,actor_role text,old_values jsonb,new_values jsonb,request_id text,ip_address inet);
create table audit_log(id bigint primary key,organization_id uuid,at timestamptz,table_name text,action text,record_id uuid,actor_id uuid,actor_role text,before jsonb,after jsonb);
create table whatsapp_messages(id uuid,organization_id uuid,failed_at timestamptz,created_at timestamptz,status text,member_id uuid,template_name text,template_key text,error_code text,error_message text,attempts integer,origin text);
create table platform_payments(id uuid,organization_id uuid,paid_at timestamptz,created_at timestamptz,initiated_by uuid,status text,amount_minor bigint,currency text,provider text,invoice_number text,period_start timestamptz,period_end timestamptz);
create table system_alerts(id uuid,organization_id uuid,created_at timestamptz,severity text,title text,message text);
create table bulk_communication_runs(id uuid,organization_id uuid,completed_at timestamptz,created_at timestamptz,initiated_by uuid,status text,error_message text,sent_count integer,failed_count integer,total_recipients integer);
create function app.org_webhook_events(uuid,timestamptz) returns table(id uuid,received_at timestamptz,amount_minor bigint,event_type text,processing_error text,signature_verified boolean,attempts integer) language sql as $$select null::uuid,null::timestamptz,null::bigint,null::text,null::text,null::boolean,null::integer where false$$;
insert into organizations values('${org}'),('${other}');
insert into staff_memberships values('00000000-0000-4000-8000-000000000004','${org}','${actor}','Asha','Rao','asha@example.com','owner','active',now()),('00000000-0000-4000-8000-000000000005','${org}','${actor}','Asha','Rao','asha@example.com','owner','active',now());
insert into members values('${member}','${org}','Kai','Green',null);
select set_config('test.admin','true',false),set_config('test.permission','true',false);
`);
const source=fs.readFileSync(path.join(process.cwd(),'supabase/migrations/20260930170100_gym_operations_reads.sql'),'utf8');
await db.exec(source.slice(source.indexOf('create or replace function app.timeline_category('),source.indexOf('create or replace function public.admin_gym_timeline(')));
await db.exec(fs.readFileSync(path.join(process.cwd(),'supabase/migrations/1029_admin_gym_activity_read.sql'),'utf8'));
async function audit(id, entity, old, next, actorId=actor, role='owner', oid=org, action=entity+'.update') {
  await db.query(`insert into admin_audit_log(id,admin_id,action,target_organization_id,at,metadata,detail,entity_type,entity_id,actor_role,old_values,new_values) values($1,$2,$3,$4,'2026-10-09T05:00:00Z','{"source":"database_trigger"}','{"operation":"UPDATE"}',$5,$6,$7,$8,$9)`,[id,actorId,action,oid,entity,entity==='members'? member : org,role,old,next]);
}
await audit(1,'organizations',{deletion_requested_at:null},{deletion_requested_at:'2026-10-09T05:00:00Z'});
await audit(2,'members',{avatar_path:'private/a.webp',avatar_url:'https://private.example/a?token=123'}, {avatar_path:'private/b.webp',avatar_url:'https://private.example/b?token=456',nested:{password:'never-send'}});
await audit(3,'payments',{invoice_number:null,member_id:member},{invoice_number:'INV-1',member_id:member});
await audit(4,'payments',{amount_minor:100000,member_id:member},{amount_minor:150000,member_id:member});
await audit(5,'members',{first_name:'Deleted',last_name:'Member'},{first_name:'Deleted',last_name:'Member',status:'left'});
await db.exec(`update admin_audit_log set entity_id='00000000-0000-4000-8000-000000000099' where id=5;`);
await audit(6,'members',{}, {first_name:'Foreign'}, actor, 'owner', other);
await audit(7,'organizations',{}, {name:'Former actor'}, '00000000-0000-4000-8000-000000000098','system');
await audit(8,'organizations',{}, {name:'Unknown actor'}, null,null);
await audit(9,'organizations',{}, {name:'System task'}, null,'system');
await db.query(`insert into audit_log values(1,$1,'2026-10-01T05:00:00Z','expenses','UPDATE',$2,$3,'owner','{"name":"Yoga mats"}','{"name":"Exercise mats"}')`,[org,member,actor]);
async function activity(args={}) {
  const values={p_organization_id:org,...args}; const entries=Object.entries(values);
  const r=await db.query(`select public.admin_gym_activity(${entries.map(([key],i)=>key+'=> $'+(i+1)).join(',')}) as result`,entries.map(([,value])=>value));
  return r.rows[0].result;
}
const all=await activity();
assert.equal(all.total,9,'actor join does not duplicate events; foreign gym excluded');
assert.equal(all.rows.length,9);
assert(!all.rows.some(r=>r.event_id==='audit:6'));
assert(!JSON.stringify(all).includes('private/'));
assert(!JSON.stringify(all).includes('private.example'));
assert(!JSON.stringify(all).includes('never-send'));
const photo=all.rows.find(r=>r.event_id==='audit:2');
assert(photo.changed_fields.includes('avatar_path'));
assert.equal(photo.old_values.avatar_path,'Photo set');
assert.equal(photo.new_values.avatar_path,'Photo set');
const names=await activity({p_search:'Deleted Member'});
assert.equal(names.total,1,'deleted snapshot searchable across entire dataset');
assert.equal(names.rows[0].member_exists,false);
const expense=await activity({p_search:'Exercise mats',p_category:'expenses'});
assert.equal(expense.total,1);
assert.equal((await activity({p_actor_search:'Asha',p_actor_type:'owner'})).total,6);
assert.equal((await activity({p_category:'payments'})).total,2);
assert.equal((await activity({p_from:'2026-10-09T00:00:00Z'})).total,8);
assert.equal((await activity({p_status:'failed'})).total,0);
const empty=await activity({p_offset:100,p_limit:2});
assert.equal(empty.total,9); assert.deepEqual(empty.rows,[]);
const p1=await activity({p_limit:2}); const p2=await activity({p_limit:2,p_offset:2});
assert.equal(new Set([...p1.rows,...p2.rows].map(r=>r.event_id)).size,4);
assert.deepEqual((await activity({p_limit:2})).rows.map(r=>r.event_id),p1.rows.map(r=>r.event_id));
assert.equal((await activity({p_sort_dir:'asc'})).rows[0].event_id,'tenant:1');
assert.equal(all.rows.find(r=>r.event_id==='audit:7').actor_type,'unknown');
assert.equal(all.rows.find(r=>r.event_id==='audit:8').actor_label,'Actor not recorded');
assert.equal(all.rows.find(r=>r.event_id==='audit:9').actor_type,'system');
assert.equal(all.rows.find(r=>r.event_id==='audit:9').origin,'System');
assert.equal((await activity({p_actor_search:'asha@example.com'})).total,6);
const grouped=await activity({p_group_by_member:true});
assert.equal(grouped.total,7); assert.equal(grouped.event_total,9);
assert.equal(grouped.rows.find(r=>r.member_id===member).group_count,3);
assert.equal((await activity({p_group_by_member:true,p_category:'payments'})).rows[0].group_count,2);
assert.equal((await activity({p_member_id:member})).total,3);
assert.equal((await activity({p_member_id:member,p_category:'payments'})).total,2);
for(let id=10;id<40;id++) await audit(id,'payments',{member_id:member,amount_minor:id*100},{member_id:member,amount_minor:(id+1)*100});
const many=await activity({p_group_by_member:true});
assert.equal(many.total,7,'member group stays one entry across the full dataset');
assert.equal(many.event_total,39);
assert.equal(many.rows.find(r=>r.member_id===member).group_count,33);
const original1=await activity({p_member_id:member,p_limit:25});
const original2=await activity({p_member_id:member,p_limit:25,p_offset:25});
assert.equal(new Set([...original1.rows,...original2.rows].map(r=>r.event_id)).size,33,'every original grouped event remains accessible across expansion pages');
const sameNameMember='00000000-0000-4000-8000-000000000007';
await db.query('insert into members values($1,$2,$3,$4,null)',[sameNameMember,org,'Kai','Green']);
await audit(40,'members',{}, {first_name:'Kai',last_name:'Green'});
await db.query('update admin_audit_log set entity_id=$1 where id=40',[sameNameMember]);
const sameNames=await activity({p_group_by_member:true,p_search:'Kai Green'});
assert.equal(sameNames.total,2,'members with the same name stay in separate identity groups');
assert.equal(new Set(sameNames.rows.map(row=>row.member_id)).size,2);
await db.exec(`select set_config('test.permission','false',false);`);
await assert.rejects(activity(), /Not authorized/);
await db.exec(`select set_config('test.permission','true',false),set_config('test.admin','false',false);`);
await assert.rejects(activity(), /Not authorized/);
const acl=await db.query(`select has_function_privilege('anon','public.admin_gym_activity(uuid,text,text,text,text,timestamptz,timestamptz,text,integer,integer,text,uuid,boolean)','execute') as anon,has_function_privilege('authenticated','app.activity_safe_value(jsonb,text)','execute') as helper;`);
assert.equal(acl.rows[0].anon,false); assert.equal(acl.rows[0].helper,false);
console.log('Local PostgreSQL fixture passed: migration execution, isolation, permissions, filters, stable pagination, empty-page totals, redaction, actor attribution, full-dataset member grouping and paged access to all 33 original member events.');
await db.close();
