-- GENERATED by node scripts/build-gym-deletion-sql.cjs; edit the source scripts instead.
-- DEV Supabase SQL Editor: https://supabase.com/dashboard/project/pgedlnxuuelmtpmbkdwm/sql/new
-- Copy this ENTIRE file into a new SQL Editor query and run it as postgres.
-- This script stores worker configuration, enables requests and starts automatic cleanup.
-- Existing due jobs may be purged immediately. Finish the DEV rehearsal before PROD activation.
-- Run separately in the intended project AFTER deploying and rehearsing.
-- Vault values are configured below; never save filled-in tokens to source control.
-- gym_deletion_worker_url: canonical admin URL ending in
--   /api/cron/gym-deletions?environment=dev (or environment=prod)
-- gym_deletion_cron_secret: same as GYM_DELETION_CRON_SECRET_DEV/PROD
-- Optional vercel_protection_bypass for protected development deployments.
begin;

-- Refuse the wrong project before changing anything.
do $environment_check$
begin
  if not exists (
    select 1 from public.disaster_recovery_config
    where singleton and environment='development'
      and database_identifier='pgedlnxuuelmtpmbkdwm'
  ) then
    raise exception 'STOP: this script is only for DEV (pgedlnxuuelmtpmbkdwm). Do not change the environment marker to bypass this check.';
  end if;
end $environment_check$;

-- STEP 2: only after deploying BOTH apps, configuring storage and verifying worker readiness.
-- Replace the secret BELOW with the matching admin deployment environment variable.
-- Edit the origin if your canonical admin deployment uses a different HTTPS host.
-- Use a fresh SQL Editor query; never save real secrets back to this repository.
do $worker_configuration$
declare
  admin_origin text := 'https://admin.myfitdesk.app';
  worker_secret text := 'REPLACE_WITH_GYM_DELETION_CRON_SECRET_DEV';
  worker_url text;
  secret_id uuid;
begin
  if worker_secret like '%REPLACE_WITH%' or length(worker_secret)<32
    or worker_secret<>btrim(worker_secret) then
    raise exception 'Set the matching GYM_DELETION_CRON_SECRET_DEV first (at least 32 characters, no surrounding spaces).';
  end if;
  if admin_origin !~ '^https://[^/[:space:]]+$' then
    raise exception 'Use the canonical admin HTTPS origin without a path or trailing slash.';
  end if;
  worker_url := admin_origin || '/api/cron/gym-deletions?environment=dev';
  select id into secret_id from vault.secrets where name='gym_deletion_worker_url';
  if secret_id is null then
    perform vault.create_secret(worker_url,'gym_deletion_worker_url','DEV gym deletion worker');
  else
    perform vault.update_secret(secret_id,worker_url,'gym_deletion_worker_url','DEV gym deletion worker');
  end if;
  select id into secret_id from vault.secrets where name='gym_deletion_cron_secret';
  if secret_id is null then
    perform vault.create_secret(worker_secret,'gym_deletion_cron_secret','DEV gym deletion authorization');
  else
    perform vault.update_secret(secret_id,worker_secret,'gym_deletion_cron_secret','DEV gym deletion authorization');
  end if;
  -- Existing vercel_protection_bypass is preserved for protected deployments.
end $worker_configuration$;
create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;
create or replace function app.dispatch_gym_deletion_worker() returns void
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare worker_url text; worker_secret text; bypass text; headers jsonb; expected_mode text;
begin
  if not (select enabled from public.gym_deletion_config where singleton) then return; end if;
  select decrypted_secret into worker_url from vault.decrypted_secrets where name='gym_deletion_worker_url';
  select decrypted_secret into worker_secret from vault.decrypted_secrets where name='gym_deletion_cron_secret';
  select decrypted_secret into bypass from vault.decrypted_secrets where name='vercel_protection_bypass';
  select case environment when 'development' then 'dev' when 'production' then 'prod' end into expected_mode from public.disaster_recovery_config where singleton;
  if worker_url is null or worker_url !~ '^https://[^/]+/api/cron/gym-deletions\?environment=(dev|prod)$' or length(coalesce(worker_secret,''))<32 then raise exception 'Gym deletion scheduler is not configured'; end if;
  if expected_mode is null or worker_url not like '%?environment='||expected_mode then raise exception 'Deletion scheduler points to the wrong environment'; end if;
  headers:=jsonb_build_object('Authorization','Bearer '||worker_secret,'Content-Type','application/json');
  if bypass is not null then headers:=headers||jsonb_build_object('x-vercel-protection-bypass',bypass); end if;
  perform net.http_post(url:=worker_url,headers:=headers,body:='{}'::jsonb,timeout_milliseconds:=300000);
end $$;
revoke all on function app.dispatch_gym_deletion_worker() from public,anon,authenticated,service_role;
do $$ begin
  if not exists(select 1 from vault.decrypted_secrets where name='gym_deletion_worker_url') or not exists(select 1 from vault.decrypted_secrets where name='gym_deletion_cron_secret' and length(decrypted_secret)>=32) then
    raise exception 'Configure and verify the environment-specific worker before activation';
  end if;
  if exists(select 1 from cron.job where jobname='purge-expired-gyms') then perform cron.unschedule('purge-expired-gyms'); end if;
  perform cron.schedule('purge-expired-gyms','*/15 * * * *','select app.dispatch_gym_deletion_worker()');
end $$;
update public.gym_deletion_config set enabled=true where singleton;
select app.dispatch_gym_deletion_worker();
commit;

-- Expected: enabled=true; one active job with the 15-minute schedule.
select default_days,enabled from public.gym_deletion_config;
select jobname,schedule,active from cron.job where jobname='purge-expired-gyms';
-- Cron success confirms dispatch only; check the worker's HTTP result separately.
select r.status_code,r.timed_out,r.error_msg,r.created
from net._http_response r
where r.id in (
  select max(x.id) from net._http_response x
)
order by r.created desc;
-- Responses arrive asynchronously after COMMIT. Re-run the last query if it is empty.
-- This is the latest pg_net response; correlate its request with worker logs if other jobs use pg_net.
