-- GENERATED by node scripts/build-gym-deletion-sql.cjs; edit the source scripts instead.
-- PROD Supabase SQL Editor: https://supabase.com/dashboard/project/clbphruocsqsmklmrloq/sql/new
-- Copy this ENTIRE file into a new SQL Editor query and run it as postgres.
-- This script stores worker configuration, enables requests and starts automatic cleanup.
-- Existing due jobs may be purged immediately. Finish the DEV rehearsal before PROD activation.
-- Run separately in the intended project AFTER installing 1027 AND 1028,
-- deploying and rehearsing. Idle/future jobs do not invoke the app worker.
-- Vault values are configured below; never save filled-in tokens to source control.
-- gym_deletion_worker_url: canonical admin URL ending in
--   /api/cron/gym-deletions?environment=dev (or environment=prod)
-- gym_deletion_cron_secret: same as GYM_DELETION_CRON_SECRET_DEV/PROD
-- Optional vercel_protection_bypass for protected development deployments.
begin;

-- Refuse the wrong project before changing anything.
do $environment_check$
begin
  if not exists (
    select 1 from public.disaster_recovery_config
    where singleton and environment='production'
      and database_identifier='clbphruocsqsmklmrloq'
  ) then
    raise exception 'STOP: this script is only for PROD (clbphruocsqsmklmrloq). Do not change the environment marker to bypass this check.';
  end if;
end $environment_check$;

-- STEP 2: only after deploying BOTH apps, configuring storage and verifying worker readiness.
-- Replace the secret BELOW with the matching admin deployment environment variable.
-- Edit the origin if your canonical admin deployment uses a different HTTPS host.
-- Use a fresh SQL Editor query; never save real secrets back to this repository.
do $worker_configuration$
declare
  admin_origin text := 'https://admin.myfitdesk.app';
  worker_secret text := 'REPLACE_WITH_GYM_DELETION_CRON_SECRET_PROD';
  worker_url text;
  secret_id uuid;
begin
  if worker_secret like '%REPLACE_WITH%' or length(worker_secret)<32
    or worker_secret<>btrim(worker_secret) then
    raise exception 'Set the matching GYM_DELETION_CRON_SECRET_PROD first (at least 32 characters, no surrounding spaces).';
  end if;
  if admin_origin !~ '^https://[^/[:space:]]+$' then
    raise exception 'Use the canonical admin HTTPS origin without a path or trailing slash.';
  end if;
  worker_url := admin_origin || '/api/cron/gym-deletions?environment=prod';
  select id into secret_id from vault.secrets where name='gym_deletion_worker_url';
  if secret_id is null then
    perform vault.create_secret(worker_url,'gym_deletion_worker_url','PROD gym deletion worker');
  else
    perform vault.update_secret(secret_id,worker_url,'gym_deletion_worker_url','PROD gym deletion worker');
  end if;
  select id into secret_id from vault.secrets where name='gym_deletion_cron_secret';
  if secret_id is null then
    perform vault.create_secret(worker_secret,'gym_deletion_cron_secret','PROD gym deletion authorization');
  else
    perform vault.update_secret(secret_id,worker_secret,'gym_deletion_cron_secret','PROD gym deletion authorization');
  end if;
  -- Existing vercel_protection_bypass is preserved for protected deployments.
end $worker_configuration$;
do $$
declare worker_url text; worker_secret text; expected_mode text;
begin
  if to_regclass('app.gym_deletion_dispatch') is null then
    raise exception 'Install gym deletion scheduler migration 1028 before activation';
  end if;
  select decrypted_secret into worker_url from vault.decrypted_secrets where name='gym_deletion_worker_url';
  select decrypted_secret into worker_secret from vault.decrypted_secrets where name='gym_deletion_cron_secret';
  select case environment when 'development' then 'dev' when 'production' then 'prod' end into expected_mode from public.disaster_recovery_config where singleton;
  if worker_url is null or worker_url !~ '^https://[^/]+/api/cron/gym-deletions\?environment=(dev|prod)$' or length(coalesce(worker_secret,''))<32 then raise exception 'Configure and verify the environment-specific worker before activation'; end if;
  if expected_mode is null or worker_url not like '%?environment='||expected_mode then raise exception 'Deletion scheduler points to the wrong environment'; end if;
end $$;
update public.gym_deletion_config set enabled=true where singleton;
-- Dispatch only if work is already due; otherwise arm its deadline or stay idle.
select app.dispatch_gym_deletion_worker();
commit;

-- Expected: enabled=true. Deadline job is inactive when no work remains.
-- Read-only scheduler checks. No secrets or worker tokens are returned.
select default_days,enabled from public.gym_deletion_config where singleton;
select jobname,schedule,active from cron.job
where jobname in ('purge-expired-gyms','recover-gym-deletion-dispatch') order by jobname;
select wake_at,request_id,requested_at,retry_not_before,failures,last_status,last_error
from app.gym_deletion_dispatch where singleton;
select has_table_privilege('authenticated','app.gym_deletion_dispatch','select') as journal_access_must_be_false,
  has_function_privilege('authenticated','app.dispatch_gym_deletion_worker()','execute') as dispatch_access_must_be_false;
-- The deadline job is inactive when disabled/idle; the hourly DB-only recovery
-- job remains active. A future calendar schedule is expected for pending work.

-- HTTP result for the currently tracked request only; idle/future work has none.
select r.status_code,r.timed_out,r.error_msg,r.created
from net._http_response r
join app.gym_deletion_dispatch d on d.singleton and d.request_id=r.id
order by r.created desc;
-- Responses arrive asynchronously after COMMIT and are consumed by the timer.
-- Journal last_status/last_error retain the last result without exposing secrets.
