-- GENERATED by node scripts/build-gym-deletion-sql.cjs; edit the source scripts instead.
-- PROD Supabase SQL Editor: https://supabase.com/dashboard/project/clbphruocsqsmklmrloq/sql/new
-- Copy this ENTIRE file into a new SQL Editor query and run it as postgres.
-- STEP 1: installation. No placeholders; new installations stay disabled.
-- Prerequisite: existing admin migrations through 1026 and a verified platform backup.
-- Re-running preserves any already enabled configuration and existing deletion jobs.
-- Shared database: admin + FitDeskApp. No historical requests are enrolled.
-- Activation is explicit: configure worker/scheduler, verify, then enable.
begin;

-- Refuse the wrong project before changing anything.
do $environment_check$
begin
  if not exists (
    select 1 from public.disaster_recovery_config
    where singleton and environment='production'
      and database_identifier='clbphruocsqsmklmrloq'
  ) then
    raise exception 'STOP: this script is only for PROD (clbphruocsqsmklmrloq). Do not change the environment marker to bypass this check.';
  end if;
end $environment_check$;
create table if not exists public.gym_deletion_config (
  singleton boolean primary key default true check(singleton),
  enabled boolean not null default false,
  default_days integer not null default 7 check(default_days between 3 and 7)
);
insert into public.gym_deletion_config(singleton) values(true) on conflict do nothing;
create table if not exists public.gym_deletion_jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null, -- deliberately no FK: minimal completion receipt survives
  requested_at timestamptz not null,
  purge_after timestamptz not null,
  requested_by uuid,
  reason text,
  state text not null default 'quarantined' check(state in ('quarantined','purging','restored','completed')),
  lease_token uuid,
  lease_until timestamptz,
  database_deleted_at timestamptz,
  completed_at timestamptz,
  user_ids uuid[] not null default '{}',
  attempts integer not null default 0,
  last_error text,
  check(purge_after >= requested_at + interval '3 days' and purge_after <= requested_at + interval '7 days')
);
create unique index if not exists gym_deletion_one_live on public.gym_deletion_jobs(organization_id) where state in ('quarantined','purging');
create index if not exists gym_deletion_due on public.gym_deletion_jobs(purge_after) where state in ('quarantined','purging');
alter table public.gym_deletion_config enable row level security;
alter table public.gym_deletion_config force row level security;
alter table public.gym_deletion_jobs enable row level security;
alter table public.gym_deletion_jobs force row level security;
revoke all on public.gym_deletion_config, public.gym_deletion_jobs from public,anon,authenticated;
grant select(id,organization_id,requested_at,purge_after,state,completed_at,database_deleted_at,last_error,attempts) on public.gym_deletion_jobs to authenticated;
drop policy if exists deletion_admin_read on public.gym_deletion_jobs;
create policy deletion_admin_read on public.gym_deletion_jobs for select to authenticated using(app.has_platform_permission('gyms.view'));
grant all on public.gym_deletion_config, public.gym_deletion_jobs to service_role;

create or replace function app.gym_is_isolated(p_org uuid) returns boolean
language sql stable security definer set search_path=pg_catalog,public,app as $$
  select exists(select 1 from public.organizations where id=p_org and deletion_requested_at is not null)
    or exists(select 1 from public.gym_deletion_jobs where organization_id=p_org and state in ('quarantined','purging','completed'));
$$;
revoke all on function app.gym_is_isolated(uuid) from public,anon;
grant execute on function app.gym_is_isolated(uuid) to authenticated,service_role;

-- The trigger also catches old owner clients and Recovery's restore RPC.
create or replace function app.track_gym_deletion() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare j public.gym_deletion_jobs; days integer;
begin
  if new.deletion_requested_at is not distinct from old.deletion_requested_at then return new; end if;
  if exists(select 1 from public.gym_deletion_jobs where organization_id=old.id and state='completed') then raise exception 'This gym was already permanently deleted'; end if;
  select * into j from public.gym_deletion_jobs where organization_id=old.id and state in ('quarantined','purging') for update;
  if old.deletion_requested_at is not null then
    if new.deletion_requested_at is not null then raise exception 'The deletion deadline cannot be changed'; end if;
    if j.id is not null and (j.state<>'quarantined' or clock_timestamp()>=j.purge_after) then
      raise exception 'The recovery window has ended. This gym can no longer be restored';
    end if;
    update public.gym_deletion_jobs set state='restored', reason=null,requested_by=null,last_error=null,user_ids='{}' where id=j.id;
    return new;
  end if;
  if not (select enabled from public.gym_deletion_config where singleton) then
    raise exception 'Gym deletion is not enabled until automatic cleanup is configured';
  end if;
  if to_regclass('public.platform_billing_operations') is not null then
    if exists(select 1 from public.platform_billing_operations where organization_id=old.id and state in ('reserved','submitted','linked')) then
      raise exception 'Cancel and reconcile AutoPay before requesting gym deletion';
    end if;
  end if;
  select default_days into days from public.gym_deletion_config where singleton;
  -- RPC may have inserted a validated request; otherwise default to 7 days.
  if j.id is null then
    new.deletion_requested_at:=clock_timestamp();
    insert into public.gym_deletion_jobs(organization_id,requested_at,purge_after,requested_by,reason)
      values(new.id,new.deletion_requested_at,new.deletion_requested_at+make_interval(days=>days),auth.uid(),'Owner deletion request');
  else new.deletion_requested_at:=j.requested_at;
  end if;
  return new;
end $$;
drop trigger if exists track_gym_deletion on public.organizations;
create trigger track_gym_deletion before update of deletion_requested_at on public.organizations for each row execute function app.track_gym_deletion();

-- Do not let one isolated gym make a shared batch fail for all other gyms.
-- Patch only known claim predicates; unrecognized installed definitions abort
-- the migration instead of silently claiming protected work.
do $$ declare r record; fn regprocedure; definition text; revised text; begin
  for r in select * from (values
    ('public.claim_whatsapp_queue_batch(integer,integer)','where m.direction =','where not app.gym_is_isolated(m.organization_id) and m.direction ='),
    ('public.claim_due_broadcast_campaigns(integer)','where status = ''queuing''','where not app.gym_is_isolated(organization_id) and status = ''queuing'''),
    ('public.claim_due_broadcast_campaigns(integer)','where status = ''scheduled''','where not app.gym_is_isolated(organization_id) and status = ''scheduled'''),
    ('public.claim_due_owner_whatsapp_organizations(integer)','where least(d.daily_at, d.credit_at)','where not app.gym_is_isolated(d.organization_id) and least(d.daily_at, d.credit_at)'),
    ('public.claim_platform_autopay_price_changes(text,integer)','where b.environment=p_environment','where not app.gym_is_isolated(b.organization_id) and b.environment=p_environment'),
    ('public.activate_due_pending_subscription_packages()','where os.pending_package_id','where not app.gym_is_isolated(os.organization_id) and os.pending_package_id')
  ) v(signature,original,replacement) loop
    fn:=to_regprocedure(r.signature);
    if fn is null then continue; end if;
    definition:=pg_get_functiondef(fn);
    if position('app.gym_purge_id' in definition)>0 then continue; end if;
    if position(r.replacement in definition)>0 then continue; end if;
    revised:=replace(definition,r.original,r.replacement);
    if revised=definition then raise exception 'Review the isolation predicate for % before installing gym deletion',r.signature; end if;
    execute revised;
  end loop;
end $$;

create or replace function public.admin_request_gym_deletion(p_organization_id uuid,p_days integer,p_reason text,p_confirmation text) returns void
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare o public.organizations; t timestamptz:=clock_timestamp();
begin
  if not app.has_platform_permission('gyms.manage') then raise exception 'Not authorized' using errcode='42501'; end if;
  if p_days is null or p_days not between 3 and 7 or length(btrim(coalesce(p_reason,''))) not between 3 and 500 then raise exception 'Choose 3–7 days and enter a reason (3–500 characters)'; end if;
  if not (select enabled from public.gym_deletion_config where singleton) then raise exception 'Automatic cleanup is not configured'; end if;
  select * into strict o from public.organizations where id=p_organization_id for update;
  if o.deletion_requested_at is not null then raise exception 'Gym is already pending deletion'; end if;
  if p_confirmation is distinct from o.name then raise exception 'Type the gym name exactly to confirm'; end if;
  insert into public.gym_deletion_jobs(organization_id,requested_at,purge_after,requested_by,reason)
    values(o.id,t,t+make_interval(days=>p_days),auth.uid(),btrim(p_reason));
  update public.organizations set deletion_requested_at=t where id=o.id;
  insert into public.admin_audit_log(admin_id,action,target_organization_id,detail)
    values(auth.uid(),'organization.deletion_requested',o.id,jsonb_build_object('days',p_days,'purge_after',t+make_interval(days=>p_days),'reason',btrim(p_reason)));
end $$;

create or replace function public.restore_gym_deletion(p_organization_id uuid) returns void
language plpgsql security definer set search_path=pg_catalog,public,app as $$
begin
  if not app.has_platform_permission('gyms.manage') and not exists(select 1 from public.staff_memberships
    where organization_id=p_organization_id and user_id=auth.uid() and role='owner' and access_status='active' and deletion_requested_at is null) then
    raise exception 'Only the gym owner or an authorized admin may restore this gym' using errcode='42501';
  end if;
  -- Lock order matches request and worker: organization first, job second.
  perform 1 from public.organizations where id=p_organization_id for update;
  update public.organizations set deletion_requested_at=null where id=p_organization_id and deletion_requested_at is not null;
  if not found then raise exception 'Gym is not pending deletion'; end if;
  insert into public.admin_audit_log(admin_id,action,target_organization_id,detail)
    values(auth.uid(),'organization.deletion_restored',p_organization_id,'{}');
end $$;

create or replace function public.gym_deletion_status(p_organization_id uuid) returns jsonb
language plpgsql stable security definer set search_path=pg_catalog,public,app as $$
begin
  if not app.has_platform_permission('gyms.view') and not exists(select 1 from public.staff_memberships where organization_id=p_organization_id and user_id=auth.uid()) then
    raise exception 'Not authorized' using errcode='42501';
  end if;
  return (select jsonb_build_object('requestedAt',requested_at,'purgeAfter',purge_after,'state',state,
    'canRestore',state='quarantined' and clock_timestamp()<purge_after,'hasError',last_error is not null)
    from public.gym_deletion_jobs where organization_id=p_organization_id and state in ('quarantined','purging') limit 1);
end $$;

-- Restrictive policies compose with existing tenant policies. Admin reads and
-- the narrow organization/membership reads needed for recovery stay available.
-- Writes from background service clients are blocked by a trigger as well.
create or replace function app.guard_isolated_gym_write() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare row_data jsonb:=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end; org uuid;
begin
  org:=case when tg_table_name='organizations' then (row_data->>'id')::uuid else coalesce((row_data->>'organization_id')::uuid,(row_data->>'org_id')::uuid) end;
  if tg_table_name='organizations' and tg_op='UPDATE' and (to_jsonb(old)->>'deletion_requested_at') is distinct from (to_jsonb(new)->>'deletion_requested_at')
    and (to_jsonb(old)-array['deletion_requested_at','updated_at'])=(to_jsonb(new)-array['deletion_requested_at','updated_at']) then return new; end if;
  if app.gym_is_isolated(org) and not (tg_op='DELETE' and current_setting('app.gym_purge_id',true)=org::text
      and exists(select 1 from public.gym_deletion_jobs where organization_id=org and state='purging' and database_deleted_at is null and lease_token::text=current_setting('app.gym_purge_token',true))) then
    raise exception 'This gym is isolated pending deletion' using errcode='42501';
  end if;
  if tg_op='UPDATE' and app.gym_is_isolated(coalesce((to_jsonb(old)->>'organization_id')::uuid,(to_jsonb(old)->>'org_id')::uuid))
     and org is distinct from coalesce((to_jsonb(old)->>'organization_id')::uuid,(to_jsonb(old)->>'org_id')::uuid) then raise exception 'Cannot move an isolated gym record'; end if;
  return case when tg_op='DELETE' then old else new end;
end $$;
do $$ declare r record; col text; begin
  for r in select c.oid,n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname in ('public','app') and c.relkind='r' and c.relname not in ('gym_deletion_jobs','admin_audit_log','system_alerts','audit_log')
  loop
    select a.attname into col from pg_attribute a where a.attrelid=r.oid and a.attname in ('organization_id','org_id') and a.atttypid='uuid'::regtype and not a.attisdropped limit 1;
    if r.relname='organizations' then col:='id'; end if;
    if col is null then continue; end if;
    execute format('alter table %I.%I enable row level security',r.nspname,r.relname);
    execute format('drop policy if exists gym_deletion_isolation on %I.%I',r.nspname,r.relname);
    execute format('drop policy if exists gym_deletion_staff_read on %I.%I',r.nspname,r.relname);
    execute format('drop trigger if exists guard_isolated_gym on %I.%I',r.nspname,r.relname);
    if r.relname not in ('staff_memberships','organizations') then
      execute format('create policy gym_deletion_isolation on %I.%I as restrictive for all to authenticated using (not app.gym_is_isolated(%I) or app.is_platform_admin()) with check (not app.gym_is_isolated(%I))',r.nspname,r.relname,col,col);
    elsif r.relname='staff_memberships' then
      execute format('create policy gym_deletion_staff_read on %I.%I as restrictive for select to authenticated using (not app.gym_is_isolated(%I) or user_id=auth.uid() or app.is_platform_admin())',r.nspname,r.relname,col);
    end if;
    execute format('create trigger guard_isolated_gym before insert or update or delete on %I.%I for each row execute function app.guard_isolated_gym_write()',r.nspname,r.relname);
  end loop;
end $$;

-- Indirect children (read marks, campaign recipients, CRM activities, etc.)
-- need isolation too, even when their old policy only checks a user ID.
create or replace function app.gym_row_isolated(p_rel oid,p_row jsonb,p_target uuid default null,p_seen text[] default '{}') returns boolean
language plpgsql stable security definer set search_path=pg_catalog,public,app as $$
declare key text; org uuid; edge record; predicate text; parent_data jsonb; fingerprint text:=p_rel::text||':'||md5(p_row::text);
begin
  if fingerprint=any(p_seen) then return false; end if;
  if cardinality(p_seen)>32 then raise exception 'Isolation relationship requires review'; end if;
  p_seen:=array_append(p_seen,fingerprint);
  foreach key in array array['organization_id','org_id','target_organization_id'] loop
    org:=(p_row->>key)::uuid;
    if org is not null and (case when p_target is null then app.gym_is_isolated(org) else org=p_target end) then return true; end if;
  end loop;
  if p_rel='public.organizations'::regclass then
    org:=(p_row->>'id')::uuid;
    return case when p_target is null then app.gym_is_isolated(org) else org=p_target end;
  end if;
  for edge in select c.*,n.nspname,t.relname from pg_constraint c join pg_class t on t.oid=c.confrelid join pg_namespace n on n.oid=t.relnamespace
    where c.contype='f' and c.conrelid=p_rel and n.nspname in ('public','app')
  loop
    select string_agg(format('($1->%L) <> ''null''::jsonb and to_jsonb(t)->%L = $1->%L',ca.attname,pa.attname,ca.attname),' and ') into predicate
      from unnest(edge.conkey,edge.confkey) k(child,parent) join pg_attribute ca on ca.attrelid=edge.conrelid and ca.attnum=k.child join pg_attribute pa on pa.attrelid=edge.confrelid and pa.attnum=k.parent;
    execute format('select to_jsonb(t) from %I.%I t where %s',edge.nspname,edge.relname,predicate) into parent_data using p_row;
    if parent_data is not null and app.gym_row_isolated(edge.confrelid,parent_data,p_target,p_seen) then return true; end if;
  end loop;
  return false;
end $$;
revoke all on function app.gym_row_isolated(oid,jsonb,uuid,text[]) from public,anon;
grant execute on function app.gym_row_isolated(oid,jsonb,uuid,text[]) to authenticated,service_role;
create or replace function app.guard_isolated_gym_child() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare isolated boolean; target uuid:=nullif(current_setting('app.gym_purge_id',true),'')::uuid;
begin
  isolated:=app.gym_row_isolated(tg_relid,case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end);
  if tg_op='UPDATE' then isolated:=isolated or app.gym_row_isolated(tg_relid,to_jsonb(old)); end if;
  if isolated and not (tg_op='DELETE' and target is not null and app.gym_row_isolated(tg_relid,to_jsonb(old),target)
    and exists(select 1 from public.gym_deletion_jobs where organization_id=target and state='purging' and database_deleted_at is null and lease_token::text=current_setting('app.gym_purge_token',true))) then
    raise exception 'This gym is isolated pending deletion' using errcode='42501';
  end if;
  return case when tg_op='DELETE' then old else new end;
end $$;
revoke all on function app.guard_isolated_gym_child() from public,anon,authenticated,service_role;
do $$ declare r record; begin
  for r in with recursive scoped(rel) as (
    select c.oid from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app') and c.relkind='r'
      and (c.oid='public.organizations'::regclass or exists(select 1 from pg_attribute a where a.attrelid=c.oid and a.attname in ('organization_id','org_id') and a.atttypid='uuid'::regtype and not a.attisdropped))
    union
    select fk.conrelid from pg_constraint fk join scoped p on p.rel=fk.confrelid join pg_class t on t.oid=fk.conrelid join pg_namespace n on n.oid=t.relnamespace where fk.contype='f' and n.nspname in ('public','app') and t.relkind='r'
  ) select c.oid,c.relname,n.nspname from scoped s join pg_class c on c.oid=s.rel join pg_namespace n on n.oid=c.relnamespace
    where c.oid<>'public.organizations'::regclass and c.relname not in ('gym_deletion_jobs','gym_deletion_config','audit_log','admin_audit_log','system_alerts')
    and not exists(select 1 from pg_attribute a where a.attrelid=c.oid and a.attname in ('organization_id','org_id') and a.atttypid='uuid'::regtype and not a.attisdropped)
  loop
    execute format('alter table %I.%I enable row level security',r.nspname,r.relname);
    execute format('drop policy if exists gym_deletion_child_isolation on %I.%I',r.nspname,r.relname);
    execute format('create policy gym_deletion_child_isolation on %I.%I as restrictive for all to authenticated using (not app.gym_row_isolated(%s,to_jsonb(%I)) or app.is_platform_admin()) with check (not app.gym_row_isolated(%s,to_jsonb(%I)))',r.nspname,r.relname,r.oid,r.relname,r.oid,r.relname);
    execute format('drop trigger if exists guard_isolated_gym_child on %I.%I',r.nspname,r.relname);
    execute format('create trigger guard_isolated_gym_child before insert or update or delete on %I.%I for each row execute function app.guard_isolated_gym_child()',r.nspname,r.relname);
  end loop;
end $$;

create or replace function public.claim_gym_deletion(p_token uuid) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare j public.gym_deletion_jobs; org uuid; users uuid[];
begin
  if p_token is null then raise exception 'Missing worker token'; end if;
  if not (select enabled from public.gym_deletion_config where singleton) then return null; end if;
  select organization_id into org from public.gym_deletion_jobs where (state in ('quarantined','purging') or (state='completed' and exists(select 1 from public.organizations o where o.id=organization_id))) and purge_after<=clock_timestamp()
    and (lease_until is null or lease_until<clock_timestamp()) order by purge_after limit 1;
  if org is null then return null; end if;
  perform 1 from public.organizations where id=org for update;
  select * into j from public.gym_deletion_jobs where organization_id=org and (state in ('quarantined','purging') or (state='completed' and exists(select 1 from public.organizations o where o.id=org))) and purge_after<=clock_timestamp()
    and (lease_until is null or lease_until<clock_timestamp()) for update skip locked;
  if j.id is null then return null; end if;
  if j.state='quarantined' and not exists(select 1 from public.organizations where id=org and deletion_requested_at is not null) then raise exception 'Deletion state mismatch'; end if;
  users:=j.user_ids;
  if j.database_deleted_at is null or j.state='completed' then
    select array_agg(distinct user_id) filter(where user_id is not null) into users from public.staff_memberships where organization_id=org;
    if exists(select 1 from pg_attribute where attrelid=to_regclass('public.staff_invitations') and attname='phone_auth_user_id' and not attisdropped) then
      execute 'select array(select unnest($1::uuid[]) union select phone_auth_user_id from public.staff_invitations where organization_id=$2 and phone_auth_user_id is not null)' into users using coalesce(users,'{}'::uuid[]),org;
    end if;
  end if;
  update public.gym_deletion_jobs set state='purging',lease_token=p_token,lease_until=clock_timestamp()+interval '20 minutes',attempts=attempts+1,
    database_deleted_at=case when state='completed' then null else database_deleted_at end,
    completed_at=null,
    user_ids=coalesce(users,'{}'::uuid[])
    where id=j.id returning * into j;
  return to_jsonb(j)-array['reason','requested_by','last_error'];
end $$;

create or replace function app.assert_gym_deletion_lease(p_id uuid,p_token uuid) returns public.gym_deletion_jobs
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare j public.gym_deletion_jobs;
begin
  select * into j from public.gym_deletion_jobs where id=p_id and state='purging' and lease_token=p_token and lease_until>clock_timestamp() for update;
  if j.id is null or j.purge_after>clock_timestamp() then raise exception 'Invalid or expired deletion lease'; end if;
  update public.gym_deletion_jobs set lease_until=clock_timestamp()+interval '20 minutes' where id=j.id;
  return j;
end $$;

create or replace function public.check_gym_deletion_storage(p_id uuid,p_token uuid) returns void
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare j public.gym_deletion_jobs; r record; predicate text; shared boolean;
begin
  j:=app.assert_gym_deletion_lease(p_id,p_token);
  -- Historical bad asset links must not cause another gym to lose its file.
  -- Match a complete UUID folder segment, never a loose partial ID prefix.
  for r in select c.oid,n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app') and c.relkind='r' and c.relname<>'gym_deletion_jobs' loop
    select string_agg(format('t.%I is not null and t.%I <> $1',a.attname,a.attname),' or ') into predicate from pg_attribute a
      where a.attrelid=r.oid and a.attname in ('organization_id','org_id','target_organization_id') and a.atttypid='uuid'::regtype and not a.attisdropped;
    if predicate is null then continue; end if;
    execute format('select exists(select 1 from %I.%I t where (%s) and to_jsonb(t)::text like $2)',r.nspname,r.relname,predicate)
      into shared using j.organization_id,'%'||j.organization_id::text||'/%';
    if shared then raise exception 'The gym folder is referenced by another gym; cleanup requires review'; end if;
  end loop;
end $$;
revoke all on function public.check_gym_deletion_storage(uuid,uuid) from public,anon,authenticated;
grant execute on function public.check_gym_deletion_storage(uuid,uuid) to service_role;

-- Build a complete row-level FK closure. A child explicitly assigned to
-- another organization aborts the transaction, even for ON DELETE CASCADE.
-- Schema surprises/cycles fail closed; no constraints/triggers are disabled.
create or replace function public.purge_gym_database(p_id uuid,p_token uuid) returns void
language plpgsql security definer set search_path=pg_catalog,public,app,pg_temp set lock_timeout='5s' set statement_timeout='120s' as $$
declare j public.gym_deletion_jobs; r record; edge record; pred text; join_sql text; count_added integer; added integer; removed integer; total_removed integer; bad boolean;
begin
  j:=app.assert_gym_deletion_lease(p_id,p_token);
  if j.database_deleted_at is not null then return; end if;
  perform set_config('app.gym_purge_id',j.organization_id::text,true);
  perform set_config('app.gym_purge_token',p_token::text,true);
  create temporary table gym_purge_rows(rel oid,row_tid tid,data jsonb,primary key(rel,row_tid)) on commit drop;
  -- Lock participating application tables in OID order, keeping CTIDs stable.
  -- Other gyms are never selected; lock contention rolls back and retries.
  for r in select c.oid,n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname in ('public','app') and c.relkind='r' and c.relname not in ('gym_deletion_jobs','gym_deletion_config') order by c.oid
  loop
    execute format('lock table %I.%I in share row exclusive mode',r.nspname,r.relname);
    select string_agg(format('t.%I = $1',a.attname),' or ') into pred from pg_attribute a where a.attrelid=r.oid and not a.attisdropped and a.atttypid='uuid'::regtype
      and (a.attname in ('organization_id','org_id','target_organization_id') or (r.relname='system_alerts' and a.attname='gym_id') or (r.relname='organizations' and a.attname='id'));
    if pred is not null then execute format('insert into pg_temp.gym_purge_rows select %s,t.ctid,to_jsonb(t) from %I.%I t where %s on conflict do nothing',r.oid,r.nspname,r.relname,pred) using j.organization_id; end if;
  end loop;
  -- Personal preferences belong to an exclusive login. Actor references in
  -- surviving gyms are not ownership edges and are never swept.
  for r in select c.oid,n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('user_preferences','auth_otp_codes') and c.relkind='r' loop
    execute format('insert into pg_temp.gym_purge_rows select %s,t.ctid,to_jsonb(t) from %I.%I t
      where t.user_id=any($1) and not exists(select 1 from public.staff_memberships s where s.user_id=t.user_id and s.organization_id<>$2)
      and not exists(select 1 from public.platform_admins a where a.user_id=t.user_id) on conflict do nothing',r.oid,r.nspname,r.relname) using j.user_ids,j.organization_id;
  end loop;
  loop
    added:=0;
    for edge in select c.*,n.nspname,t.relname from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace
      where c.contype='f' and exists(select 1 from pg_temp.gym_purge_rows where rel=c.confrelid)
    loop
      if edge.nspname not in ('public','app') then raise exception 'Unexpected external schema FK: %',edge.conname; end if;
      select string_agg(format('t.%I is not null and to_jsonb(t)->%L = p.data->%L',ca.attname,ca.attname,pa.attname),' and ') into join_sql
        from unnest(edge.conkey,edge.confkey) k(child,parent)
        join pg_attribute ca on ca.attrelid=edge.conrelid and ca.attnum=k.child
        join pg_attribute pa on pa.attrelid=edge.confrelid and pa.attnum=k.parent;
      execute format('insert into pg_temp.gym_purge_rows select %s,t.ctid,to_jsonb(t) from %I.%I t join pg_temp.gym_purge_rows p on p.rel=%s and %s on conflict do nothing',edge.conrelid,edge.nspname,edge.relname,edge.confrelid,join_sql);
      get diagnostics count_added=row_count; added:=added+count_added;
    end loop;
    exit when added=0;
  end loop;
  select exists(select 1 from pg_temp.gym_purge_rows p,jsonb_each_text(p.data) e where e.key in ('organization_id','org_id','target_organization_id')
    and e.value is not null and e.value<>j.organization_id::text) into bad;
  if bad then raise exception 'Cross-gym relationship detected; nothing was deleted'; end if;
  -- Shared platform identities and recovery state must never be reached.
  if exists(select 1 from pg_temp.gym_purge_rows p join pg_class c on c.oid=p.rel where c.relname in ('platform_admins','gym_deletion_jobs','gym_deletion_config','database_backups','database_restore_history','disaster_recovery_config')) then
    raise exception 'Deletion reached a shared platform record';
  end if;
  -- Delete leaves first. FK-restrict failures are retried after children;
  -- unresolved cycles abort the entire database purge transaction.
  loop
    total_removed:=0;
    for r in select distinct p.rel,c.relname,n.nspname from pg_temp.gym_purge_rows p join pg_class c on c.oid=p.rel join pg_namespace n on n.oid=c.relnamespace order by p.rel
    loop
      begin
        execute format('delete from %I.%I t using pg_temp.gym_purge_rows p where p.rel=%s and t.ctid=p.row_tid',r.nspname,r.relname,r.rel);
        get diagnostics removed=row_count;
        delete from pg_temp.gym_purge_rows where rel=r.rel;
        total_removed:=total_removed+removed;
      exception when foreign_key_violation then null;
      end;
    end loop;
    exit when not exists(select 1 from pg_temp.gym_purge_rows);
    if total_removed=0 then raise exception 'Unresolved FK dependency; database deletion rolled back'; end if;
  end loop;
  -- Triggers may append tenant audit/alert rows during deletion; remove
  -- these exact gym-scoped records too, including organization delete events.
  for r in select c.oid,n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app') and c.relkind='r' and c.relname in ('audit_log','admin_audit_log','system_alerts') loop
    select string_agg(format('%I = $1',a.attname),' or ') into pred from pg_attribute a where a.attrelid=r.oid and not a.attisdropped and a.attname in ('organization_id','target_organization_id','gym_id') and a.atttypid='uuid'::regtype;
    if pred is not null then execute format('delete from %I.%I where %s',r.nspname,r.relname,pred) using j.organization_id; end if;
  end loop;
  update public.gym_deletion_jobs set database_deleted_at=clock_timestamp(),last_error=null where id=j.id;
end $$;

-- Skip snapshot-producing audit triggers only inside a real leased purge.
-- Preserve each function's existing definition/privileges outside that path.
do $$ declare fn regprocedure; definition text; begin
  foreach fn in array array[to_regprocedure('app.write_audit()'),to_regprocedure('app.write_platform_critical_audit()')] loop
    if fn is null then continue; end if;
    definition:=pg_get_functiondef(fn);
    definition:=regexp_replace(definition,'\mBEGIN\M', E'BEGIN\n  if TG_OP = ''DELETE'' and current_setting(''app.gym_purge_id'', true) = coalesce(to_jsonb(old)->>''organization_id'', case when TG_TABLE_NAME=''organizations'' then to_jsonb(old)->>''id'' end) and exists(select 1 from public.gym_deletion_jobs where organization_id = current_setting(''app.gym_purge_id'',true)::uuid and state=''purging'' and database_deleted_at is null) then return old; end if;', 'i');
    execute definition;
  end loop;
end $$;

create or replace function public.gym_deletion_auth_candidate(p_id uuid,p_token uuid,p_user uuid) returns boolean
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare j public.gym_deletion_jobs; r record; col text; found_reference boolean;
begin
  j:=app.assert_gym_deletion_lease(p_id,p_token);
  if j.database_deleted_at is null or not p_user=any(j.user_ids) then raise exception 'Not an eligible deletion account'; end if;
  -- A user shared with another gym, platform admin, or surviving record is
  -- retained. GoTrue owns deletion of auth identities/sessions, never SQL.
  for r in select c.conrelid,c.conkey,n.nspname,t.relname from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace
    where c.contype='f' and c.confrelid='auth.users'::regclass and n.nspname not in ('auth') and t.relname<>'gym_deletion_jobs'
  loop
    if cardinality(r.conkey)<>1 then return false; end if;
    select attname into col from pg_attribute where attrelid=r.conrelid and attnum=r.conkey[1];
    execute format('select exists(select 1 from %I.%I where %I=$1)',r.nspname,r.relname,col) into found_reference using p_user;
    if found_reference then return false; end if;
  end loop;
  return true;
end $$;
create or replace function public.finish_gym_deletion(p_id uuid,p_token uuid,p_error text default null) returns void
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare j public.gym_deletion_jobs;
begin
  j:=app.assert_gym_deletion_lease(p_id,p_token);
  if p_error is null and j.database_deleted_at is null then raise exception 'Database deletion has not completed'; end if;
  update public.gym_deletion_jobs set state=case when p_error is null then 'completed' else 'purging' end,
    completed_at=case when p_error is null then clock_timestamp() end,
    reason=case when p_error is null then null else reason end, requested_by=case when p_error is null then null else requested_by end,
    user_ids=case when p_error is null then '{}'::uuid[] else user_ids end,
    last_error=case when p_error is null then null else left(p_error,500) end,
    lease_token=null,lease_until=case when p_error is null then null else clock_timestamp()+interval '15 minutes' end where id=j.id;
end $$;

-- GoTrue executes the final auth deletion under a row lock. Recheck surviving
-- application references there too, closing the check/API-call race for users
-- who acquire a second membership or platform role during cleanup.
create or replace function app.guard_gym_deletion_auth() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,app as $$
declare r record; col text; referenced boolean;
begin
  if not exists(select 1 from public.gym_deletion_jobs where state='purging' and database_deleted_at is not null and old.id=any(user_ids)) then return old; end if;
  for r in select c.conrelid,c.conkey,n.nspname,t.relname from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace
    where c.contype='f' and c.confrelid='auth.users'::regclass and n.nspname<>'auth' and t.relname<>'gym_deletion_jobs'
  loop
    if cardinality(r.conkey)<>1 then raise exception 'Shared identity dependency requires review'; end if;
    select attname into col from pg_attribute where attrelid=r.conrelid and attnum=r.conkey[1];
    execute format('select exists(select 1 from %I.%I where %I=$1)',r.nspname,r.relname,col) into referenced using old.id;
    if referenced then raise exception 'Identity is still referenced outside the deleted gym'; end if;
  end loop;
  return old;
end $$;
drop trigger if exists guard_gym_deletion_auth on auth.users;
create trigger guard_gym_deletion_auth before delete on auth.users for each row execute function app.guard_gym_deletion_auth();
revoke all on function app.guard_gym_deletion_auth() from public,anon,authenticated,service_role;

revoke all on function app.track_gym_deletion(),app.guard_isolated_gym_write(),app.assert_gym_deletion_lease(uuid,uuid) from public,anon,authenticated;
revoke all on function public.admin_request_gym_deletion(uuid,integer,text,text),public.restore_gym_deletion(uuid),public.gym_deletion_status(uuid) from public,anon;
grant execute on function public.admin_request_gym_deletion(uuid,integer,text,text),public.restore_gym_deletion(uuid),public.gym_deletion_status(uuid) to authenticated;
revoke all on function public.claim_gym_deletion(uuid),public.purge_gym_database(uuid,uuid),public.gym_deletion_auth_candidate(uuid,uuid,uuid),public.finish_gym_deletion(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.claim_gym_deletion(uuid),public.purge_gym_database(uuid,uuid),public.gym_deletion_auth_candidate(uuid,uuid,uuid),public.finish_gym_deletion(uuid,uuid,text) to service_role;
commit;

-- Read-only installation/activation checks. Run in each intended project.
select default_days,enabled from public.gym_deletion_config;
select to_regprocedure('public.admin_request_gym_deletion(uuid,integer,text,text)') is not null as request_installed,
  to_regprocedure('public.restore_gym_deletion(uuid)') is not null as restore_installed,
  to_regprocedure('public.purge_gym_database(uuid,uuid)') is not null as purge_installed;
select has_function_privilege('authenticated','public.purge_gym_database(uuid,uuid)','execute') as must_be_false,
  has_function_privilege('service_role','public.purge_gym_database(uuid,uuid)','execute') as must_be_true,
  has_column_privilege('authenticated','public.gym_deletion_jobs','lease_token','select') as worker_token_must_be_private;
select n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
where n.nspname in ('public','app') and c.relkind='r' and c.relname not in ('gym_deletion_jobs','admin_audit_log','system_alerts','audit_log')
and exists(select 1 from pg_attribute a where a.attrelid=c.oid and a.attname in ('organization_id','org_id') and a.atttypid='uuid'::regtype and not a.attisdropped)
and not exists(select 1 from pg_trigger t where t.tgrelid=c.oid and t.tgname='guard_isolated_gym' and not t.tgisinternal);
-- The last query must return no rows. Repeat after adding tenant tables.
select state,count(*),count(*) filter(where last_error is not null) as needs_attention from public.gym_deletion_jobs group by state;
