-- ═══════════════════════════════════════════════════════════════════════
-- Gym Owner Onboarding — enables "Invite gym owner" (previously a
-- disabled placeholder, see 1009's own header and the Gyms page's own
-- comment) with a full admin-initiated create-gym-and-invite-owner flow.
--
-- NOT YET APPLIED TO ANY LIVE PROJECT (written and reviewed locally only,
-- no Supabase MCP tool or .env.local in this session — same constraint
-- several prior migrations in this file were written under). Needs the
-- same explicit go-ahead + live verification every migration in this repo
-- gets before being trusted in production (see the two "Production
-- incident" write-ups in CLAUDE.md — an unexecuted SECURITY DEFINER
-- function is not verified, static-clean or not).
--
-- Design choice, made after auditing FitDeskApp's existing staff-invite
-- machinery rather than building a parallel system: this REUSES
-- FitDeskApp's own `staff_invitations` table and its whole accept flow
-- (`/invite/accept`, the `staff_memberships_insert_via_invite` RLS policy,
-- `staff_invitations_accept_self`) completely unchanged. `role = 'owner'`
-- is already a valid value there (FitDeskApp's own check constraint has
-- allowed `'owner'` since 0002_staff_invitations.sql — it already supports
-- an existing owner inviting a co-owner; this repurposes the identical
-- path for a *platform admin* inviting a gym's very first owner, which
-- works because both apps' sessions live in the same Supabase project's
-- `auth.users` table). Concretely this means: zero new pages, zero new
-- RLS policies, and zero changes to FitDeskApp's password-setup flow are
-- needed for "owner clicks link → verifies → sets password → gets the
-- owner role" — only three small additions:
--   1. A handful of new nullable columns on `staff_invitations` (an
--      explicit `email_verified_at` timestamp, so the 3-phase progression
--      the task asked for — Invitation Sent → Email Verified → Account
--      Active — is a real, persisted state rather than inferred; plus
--      `invited_first_name`/`invited_last_name`/`invited_phone` as the
--      admin's own reference snapshot, and `resend_count`/`last_resent_at`
--      for the resend UI). All additive, `alter table ... add column if
--      not exists`, so this cannot affect FitDeskApp's own existing staff
--      invite flow in any way.
--   2. `mark_invitation_viewed()` — one new SECURITY DEFINER RPC, callable
--      by any authenticated user (self-scoped internally to the caller's
--      own email), called once by FitDeskApp's `/invite/accept/page.tsx`
--      the first time it renders for a still-`pending` invitation. This is
--      the one FitDeskApp-repo code change this migration requires — see
--      that repo's own CLAUDE.md entry for the one-line addition.
--   3. Four new admin-gated RPCs (below) that do the actual gym creation,
--      invitation lifecycle, and status read — same "SECURITY DEFINER,
--      pinned search_path, is_platform_admin() gate first, table write +
--      admin_audit_log insert in one transaction, explicit revoke-then-
--      grant" convention every prior write RPC in this file follows.
--
-- Subscription/trial setup for the new gym reuses the *existing*
-- `organization_subscriptions` row every `organizations` insert already
-- gets for free from FitDeskApp's own `app.create_default_subscription()`
-- trigger (migration 0028, a 14-day trial) — this migration only adjusts
-- that row in place to match what the admin actually chose (Free Trial
-- with a custom length / a real paid package / a custom admin-granted
-- period), never inserts a second one. Later trial/subscription management
-- (extend, change package, cancel, restore) is *already built* — see
-- `admin_extend_subscription`/`admin_change_subscription_package`/
-- `admin_cancel_subscription`/`admin_restore_subscription` in
-- 1004_admin_subscription_write_rpcs.sql — this migration adds nothing
-- new there and the admin app's Gym Detail page already exposes them via
-- `ManageSubscriptionSheet`. "Activate a trialing subscription onto a real
-- paid package" and "grant temporary/custom access" are both just that
-- existing pair of RPCs called in sequence from the app layer, not new SQL.
--
-- Gym ID: reuses FitDeskApp's own `organizations.gym_code` (migration
-- 0066_business_ids.sql, a human-readable id like "GG98701A", generated by
-- a BEFORE INSERT trigger — never a Supabase UUID shown to a user). This
-- migration does nothing to generate it; it fires automatically the moment
-- `admin_create_gym_owner_invitation` inserts into `organizations`, and is
-- read back via `returning gym_code`. `organizations` already has an
-- admin-gated SELECT policy (1002_admin_read_functions.sql), so the admin
-- app's own RLS-scoped client can read it directly with no new RPC.
-- ═══════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────
-- staff_invitations — additive columns only. All nullable/defaulted, so
-- every existing row (and every existing staff/trainer invite flow) is
-- byte-identical unless a value is explicitly set.
-- ─────────────────────────────────────────────────────────────────────────
alter table if exists public.staff_invitations
  add column if not exists email_verified_at timestamptz,
  add column if not exists invited_first_name text,
  add column if not exists invited_last_name text,
  add column if not exists invited_phone text,
  add column if not exists resend_count integer not null default 0,
  add column if not exists last_resent_at timestamptz;

-- ─────────────────────────────────────────────────────────────────────────
-- mark_invitation_viewed(p_invitation_id) — called once by FitDeskApp's
-- /invite/accept/page.tsx the first time a still-pending invitation is
-- shown to its invitee (i.e. the moment /auth/confirm's verifyOtp already
-- succeeded — Supabase itself only got them this far because the emailed
-- token was valid, so "landed here with a session" already IS "verified
-- this email"). Not gated by is_platform_admin() — the caller is the
-- brand-new owner, not an admin — self-scoped instead by matching the
-- caller's own JWT email, the same self-scoping FitDeskApp's own
-- `staff_invitations_select_self`/`staff_invitations_accept_self` RLS
-- policies already use. A SECURITY DEFINER function is required here
-- (rather than a plain RLS UPDATE) because `staff_invitations_accept_self`
-- only permits a pending→accepted transition — it cannot be used to set
-- just this one column while status stays 'pending'.
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.mark_invitation_viewed(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update staff_invitations
  set email_verified_at = now()
  where id = p_invitation_id
    and email = (select auth.jwt() ->> 'email')
    and status = 'pending'
    and email_verified_at is null;
end;
$$;

revoke execute on function public.mark_invitation_viewed(uuid) from public, anon;
grant execute on function public.mark_invitation_viewed(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- admin_create_gym_owner_invitation — the whole "Invite gym owner" submit.
-- One transaction: organizations + gyms + branches + the subscription
-- adjustment + the staff_invitations row + two admin_audit_log rows, so a
-- failure partway through (a bad package id, a duplicate email caught
-- late) leaves nothing behind — never a half-created gym. Duplicate/
-- existing-account checks run BEFORE any insert, so the common failure
-- paths (an email that's already staff somewhere, already has a pending
-- invite, or already has a Supabase Auth account with no gym role) never
-- reach the point of creating an organization at all.
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.admin_create_gym_owner_invitation(
  p_gym_name text,
  p_owner_first_name text,
  p_owner_last_name text,
  p_email text,
  p_phone text default null,
  p_address_line text default null,
  p_city text default null,
  p_state text default null,
  p_country text default null,
  p_postal_code text default null,
  p_default_timezone text default 'Asia/Kolkata',
  p_default_currency text default 'INR',
  p_billing_mode text default 'trial',
  p_trial_days integer default 14,
  p_package_id uuid default null,
  p_period_days integer default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, app, pg_temp
as $$
declare
  v_admin_id uuid := auth.uid();
  v_org_id uuid;
  v_gym_id uuid;
  v_gym_code text;
  v_slug citext;
  v_invitation_id uuid;
  v_pkg record;
  v_email citext;
begin
  if not app.is_platform_admin() then
    raise exception 'Not authorized' using errcode = 'insufficient_privilege';
  end if;

  if p_gym_name is null or btrim(p_gym_name) = '' then
    raise exception 'Enter a gym name.' using errcode = 'invalid_parameter_value';
  end if;
  if p_owner_first_name is null or btrim(p_owner_first_name) = '' then
    raise exception 'Enter the owner''s first name.' using errcode = 'invalid_parameter_value';
  end if;
  if p_email is null or btrim(p_email) = '' or p_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Enter a valid email address.' using errcode = 'invalid_parameter_value';
  end if;
  if p_billing_mode not in ('trial', 'paid', 'custom') then
    raise exception 'Choose a valid billing mode.' using errcode = 'invalid_parameter_value';
  end if;

  v_email := lower(btrim(p_email))::citext;

  -- Duplicate / existing-account checks, each a distinct admin-legible
  -- message rather than one opaque failure — "Duplicate email entered by
  -- admin", "Existing gym owner", and "Existing Supabase Auth user" are
  -- three different situations the task asks the admin to be able to
  -- tell apart.
  if exists (select 1 from staff_memberships where email = v_email) then
    raise exception 'This email already belongs to a member of an existing gym.' using errcode = 'unique_violation';
  end if;
  if exists (select 1 from staff_invitations where email = v_email and status = 'pending') then
    raise exception 'This email already has a pending invitation.' using errcode = 'unique_violation';
  end if;
  if exists (select 1 from auth.users where email = v_email) then
    raise exception 'This email already has a MyFitDesk account that is not linked to any gym yet. Resolve it manually (in Supabase Auth) before inviting it here — a brand-new invite only works for an email with no existing account.' using errcode = 'unique_violation';
  end if;

  if p_billing_mode = 'paid' then
    if p_package_id is null then
      raise exception 'Choose a subscription plan.' using errcode = 'invalid_parameter_value';
    end if;
    select * into v_pkg from platform_packages where id = p_package_id and status = 'active';
    if v_pkg.id is null then
      raise exception 'That plan is not available.' using errcode = 'invalid_parameter_value';
    end if;
  elsif p_billing_mode = 'custom' then
    if p_period_days is null or p_period_days <= 0 then
      raise exception 'Enter how many days of access to grant.' using errcode = 'invalid_parameter_value';
    end if;
  end if;

  v_slug := (regexp_replace(lower(btrim(p_gym_name)), '[^a-z0-9]+', '-', 'g') || '-' || substr(md5(random()::text), 1, 6))::citext;

  insert into organizations (
    slug, name, contact_email, contact_phone, address_line, city, state, country, postal_code,
    default_timezone, default_currency
  ) values (
    v_slug, btrim(p_gym_name), v_email, nullif(btrim(coalesce(p_phone, '')), ''),
    nullif(btrim(coalesce(p_address_line, '')), ''), nullif(btrim(coalesce(p_city, '')), ''),
    nullif(btrim(coalesce(p_state, '')), ''), nullif(btrim(coalesce(p_country, '')), ''),
    nullif(btrim(coalesce(p_postal_code, '')), ''),
    coalesce(nullif(btrim(p_default_timezone), ''), 'Asia/Kolkata'),
    coalesce(nullif(btrim(p_default_currency), ''), 'INR')
  )
  returning id, gym_code into v_org_id, v_gym_code;

  insert into gyms (organization_id, slug, name) values (v_org_id, 'main', btrim(p_gym_name))
  returning id into v_gym_id;

  insert into branches (organization_id, gym_id, name) values (v_org_id, v_gym_id, 'Main Branch');

  -- app.create_default_subscription() (FitDeskApp 0028) already inserted a
  -- 14-day trialing row on the organizations insert above —
  -- organization_subscriptions is one-row-per-org (primary keyed on
  -- organization_id), so this adjusts that row rather than inserting a
  -- second one.
  if p_billing_mode = 'trial' then
    update organization_subscriptions
    set current_period_end = now() + (greatest(coalesce(p_trial_days, 14), 1) || ' days')::interval,
        status = 'trialing'
    where organization_id = v_org_id;
  elsif p_billing_mode = 'paid' then
    update organization_subscriptions
    set package_id = v_pkg.id,
        status = 'active',
        current_period_start = now(),
        current_period_end = now() + (coalesce(p_period_days, v_pkg.duration_days) || ' days')::interval,
        cancelled_at = null
    where organization_id = v_org_id;
  else -- custom
    update organization_subscriptions
    set package_id = null,
        status = 'active',
        current_period_start = now(),
        current_period_end = now() + (p_period_days || ' days')::interval,
        cancelled_at = null
    where organization_id = v_org_id;
  end if;

  insert into staff_invitations (
    organization_id, organization_name_snapshot, branch_id, email, role, invited_by,
    invited_first_name, invited_last_name, invited_phone
  ) values (
    v_org_id, btrim(p_gym_name), null, v_email, 'owner', v_admin_id,
    nullif(btrim(p_owner_first_name), ''), nullif(btrim(coalesce(p_owner_last_name, '')), ''),
    nullif(btrim(coalesce(p_phone, '')), '')
  )
  returning id into v_invitation_id;

  insert into admin_audit_log (admin_id, action, target_organization_id, detail)
  values (
    v_admin_id, 'gym.created', v_org_id,
    jsonb_build_object(
      'gym_name', btrim(p_gym_name), 'gym_code', v_gym_code, 'billing_mode', p_billing_mode,
      'package_id', p_package_id, 'notes', nullif(btrim(coalesce(p_notes, '')), '')
    )
  );
  insert into admin_audit_log (admin_id, action, target_organization_id, detail)
  values (
    v_admin_id, 'invitation.sent', v_org_id,
    jsonb_build_object('invitation_id', v_invitation_id, 'email', v_email)
  );

  return jsonb_build_object(
    'organization_id', v_org_id,
    'gym_code', v_gym_code,
    'invitation_id', v_invitation_id,
    'email', v_email
  );
end;
$$;

revoke execute on function public.admin_create_gym_owner_invitation(
  text, text, text, text, text, text, text, text, text, text, text, text, text, integer, uuid, integer, text
) from public, anon, authenticated;
grant execute on function public.admin_create_gym_owner_invitation(
  text, text, text, text, text, text, text, text, text, text, text, text, text, integer, uuid, integer, text
) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- admin_resend_gym_owner_invitation — resets the 7-day expiry window and
-- clears email_verified_at (a resend is a fresh link; the old one's
-- "viewed" state shouldn't carry over and mask whether the NEW link was
-- ever opened). Refuses anything not currently pending — an accepted or
-- revoked invitation has nothing left to resend.
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.admin_resend_gym_owner_invitation(p_invitation_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, app, pg_temp
as $$
declare
  v_admin_id uuid := auth.uid();
  v_row record;
begin
  if not app.is_platform_admin() then
    raise exception 'Not authorized' using errcode = 'insufficient_privilege';
  end if;

  select * into v_row from staff_invitations where id = p_invitation_id and role = 'owner';
  if v_row.id is null then
    raise exception 'Invitation not found.' using errcode = 'no_data_found';
  end if;
  if v_row.status <> 'pending' then
    raise exception 'This invitation is no longer pending — it has already been accepted or revoked.' using errcode = 'invalid_parameter_value';
  end if;

  update staff_invitations
  set expires_at = now() + interval '7 days',
      email_verified_at = null,
      resend_count = coalesce(resend_count, 0) + 1,
      last_resent_at = now()
  where id = p_invitation_id
  returning * into v_row;

  insert into admin_audit_log (admin_id, action, target_organization_id, detail)
  values (v_admin_id, 'invitation.resent', v_row.organization_id, jsonb_build_object('invitation_id', v_row.id, 'email', v_row.email));

  return jsonb_build_object('email', v_row.email, 'organization_id', v_row.organization_id, 'organization_name', v_row.organization_name_snapshot);
end;
$$;

revoke execute on function public.admin_resend_gym_owner_invitation(uuid) from public, anon, authenticated;
grant execute on function public.admin_resend_gym_owner_invitation(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- admin_revoke_gym_owner_invitation — soft-stops a pending invitation
-- (matches this app's no-hard-delete convention). Deliberately does NOT
-- touch the organization/subscription it created — revoking a bad invite
-- is not the same decision as deactivating the gym, and an admin who wants
-- both can suspend the gym separately (admin_suspend_organization,
-- already built).
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.admin_revoke_gym_owner_invitation(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = public, app, pg_temp
as $$
declare
  v_admin_id uuid := auth.uid();
  v_org uuid;
begin
  if not app.is_platform_admin() then
    raise exception 'Not authorized' using errcode = 'insufficient_privilege';
  end if;

  update staff_invitations
  set status = 'revoked', revoked_at = now()
  where id = p_invitation_id and role = 'owner' and status = 'pending'
  returning organization_id into v_org;

  if v_org is null then
    raise exception 'Invitation not found, or it is no longer pending.' using errcode = 'no_data_found';
  end if;

  insert into admin_audit_log (admin_id, action, target_organization_id, detail)
  values (v_admin_id, 'invitation.revoked', v_org, jsonb_build_object('invitation_id', p_invitation_id));
end;
$$;

revoke execute on function public.admin_revoke_gym_owner_invitation(uuid) from public, anon, authenticated;
grant execute on function public.admin_revoke_gym_owner_invitation(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- admin_get_gym_owner_invitation — the read side for the Gym Detail page's
-- onboarding-status card. Returns the most recent owner invitation for a
-- gym (there is at most one *pending* one at a time, per
-- staff_invitations_pending_uq, but a resend-after-revoke history can
-- leave older rows behind — this always reads the newest). `effective_status`
-- folds "pending but past expires_at" into 'expired' and "pending with
-- email_verified_at set" into 'email_verified', so the app layer never has
-- to re-derive that logic — this is the single source of truth for the
-- "Invitation Sent → Email Verified → Account Active" progression the task
-- asked to display.
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.admin_get_gym_owner_invitation(p_organization_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, app, pg_temp
as $$
declare
  v_row record;
  v_effective text;
begin
  if not app.is_platform_admin() then
    raise exception 'Not authorized' using errcode = 'insufficient_privilege';
  end if;

  select * into v_row
  from staff_invitations
  where organization_id = p_organization_id and role = 'owner'
  order by created_at desc
  limit 1;

  if v_row.id is null then
    return null;
  end if;

  v_effective := case
    when v_row.status = 'accepted' then 'active'
    when v_row.status = 'revoked' then 'revoked'
    when v_row.status = 'pending' and v_row.expires_at < now() then 'expired'
    when v_row.status = 'pending' and v_row.email_verified_at is not null then 'email_verified'
    else 'invited'
  end;

  return jsonb_build_object(
    'id', v_row.id,
    'email', v_row.email,
    'status', v_row.status,
    'effective_status', v_effective,
    'invited_first_name', v_row.invited_first_name,
    'invited_last_name', v_row.invited_last_name,
    'invited_phone', v_row.invited_phone,
    'invited_at', v_row.created_at,
    'expires_at', v_row.expires_at,
    'email_verified_at', v_row.email_verified_at,
    'accepted_at', v_row.accepted_at,
    'revoked_at', v_row.revoked_at,
    'resend_count', coalesce(v_row.resend_count, 0),
    'last_resent_at', v_row.last_resent_at
  );
end;
$$;

revoke execute on function public.admin_get_gym_owner_invitation(uuid) from public, anon, authenticated;
grant execute on function public.admin_get_gym_owner_invitation(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- admin_gym_detail — CREATE OR REPLACE, body copied verbatim from
-- 1009_admin_gym_detail.sql, adding exactly one key: 'gym_code'. This is
-- the fix for the task's own explicit "do not expose Supabase UUIDs as the
-- user-facing Gym ID" requirement — the Gym Detail header currently prints
-- `gym_{gym.id.slice(0, 8)}` (a truncated UUID) as its "record id". Safe as
-- a plain CREATE OR REPLACE (unlike the table-returning RPCs 1010/1011 had
-- to DROP FUNCTION for): the return type is `jsonb`, so adding a key
-- doesn't change the function's signature. No other line in this body is
-- touched.
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.admin_gym_detail(p_organization_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, app, pg_temp
as $$
declare
  v_result jsonb;
begin
  if not app.is_platform_admin() then
    raise exception 'Not authorized' using errcode = 'insufficient_privilege';
  end if;

  select jsonb_build_object(
    'organization', jsonb_build_object(
      'id', o.id,
      'name', o.name,
      'slug', o.slug,
      'gym_code', o.gym_code,
      'city', o.city,
      'state', o.state,
      'country', o.country,
      'address_line', o.address_line,
      'postal_code', o.postal_code,
      'contact_email', o.contact_email,
      'contact_phone', o.contact_phone,
      'default_timezone', o.default_timezone,
      'default_currency', o.default_currency,
      'logo_url', o.logo_url,
      'grace_period_days', o.grace_period_days,
      'week_start', o.week_start,
      'opens_at', o.opens_at,
      'closes_at', o.closes_at,
      'created_at', o.created_at,
      'updated_at', o.updated_at,
      'deletion_requested_at', o.deletion_requested_at,
      'suspended_at', o.suspended_at,
      'suspension_reason', o.suspension_reason
    ),
    'owner', (
      select jsonb_build_object(
        'staff_id', sm.id,
        'name', coalesce(nullif(trim(sm.first_name || ' ' || coalesce(sm.last_name, '')), ''), sm.email::text),
        'email', sm.email::text,
        'phone', sm.phone_e164
      )
      from staff_memberships sm
      where sm.organization_id = o.id and sm.role = 'owner'
      order by sm.created_at asc
      limit 1
    ),
    'subscription', (
      select jsonb_build_object(
        'package_id', pk.id,
        'package_name', pk.name,
        'package_code', pk.code,
        'billing_period', pk.billing_period,
        'price_minor', pk.price_minor,
        'currency', pk.currency,
        'status', os.status,
        'state', app.derive_subscription_state(os.status, os.current_period_end, os.grace_days),
        'current_period_start', os.current_period_start,
        'current_period_end', os.current_period_end,
        'grace_days', os.grace_days,
        'auto_renew', os.auto_renew,
        'cancelled_at', os.cancelled_at,
        'created_at', os.created_at
      )
      from organization_subscriptions os
      left join platform_packages pk on pk.id = os.package_id
      where os.organization_id = o.id
    ),
    'usage', jsonb_build_object(
      'member_count', (select count(*) from members m where m.organization_id = o.id and m.deleted_at is null),
      'branch_count', (select count(*) from branches b where b.organization_id = o.id and b.status = 'active'),
      'staff_count', (select count(*) from staff_memberships sm2 where sm2.organization_id = o.id),
      'member_cap', pk.max_members,
      'branch_cap', pk.max_branches,
      'staff_cap', pk.max_staff
    ),
    'lifetime_paid_minor', (select coalesce(sum(pp.amount_minor), 0) from platform_payments pp where pp.organization_id = o.id and pp.status = 'succeeded'),
    'features', coalesce(pk.features, '{}')
  ) into v_result
  from organizations o
  left join organization_subscriptions os on os.organization_id = o.id
  left join platform_packages pk on pk.id = os.package_id
  where o.id = p_organization_id;

  if v_result is null then
    raise exception 'Gym not found' using errcode = 'no_data_found';
  end if;

  return v_result;
end;
$$;

revoke execute on function public.admin_gym_detail(uuid) from public, anon, authenticated;
grant execute on function public.admin_gym_detail(uuid) to authenticated;
